# Homework 1: Practical Introduction to NumPy

**Course:** 3780 Fundamentals of Data Science  
**Instructor:** Kiril Kuzmin  
**Due:** 11pm, Monday, September 14, 2026

---

## How to use this notebook
- Work top-to-bottom. Run each cell after you edit it.
- Keep your answers clear and short. Use Markdown for reasoning.
- Do not delete the problem statements.
- You may add cells as needed.
- When finished, run *Kernel → Restart & Run All*, verify outputs, then submit.

**Honor code:** Write your own code. You may discuss high-level ideas with peers, but all implementation must be yours.

In [1]:
import numpy as np


---
## Part 1. Basic Array Manipulation (20 pts)

1. Create a 1‑D NumPy array with integers from **1 to 20**.  
   - Reshape it into a **4×5** matrix.  
   - Extract:
     - the **second column**,
     - the **last row**,
     - a **2×2 sub‑matrix** from the middle (clearly state indices used).

2. Compute the **row-wise** and **column-wise** sums. Verify them against `np.sum` with the `axis` argument.


In [2]:
# === Your code for Part 1 ===
# Edit as needed, but keep variable names!

# 1) build the array and reshape (5 pts)
arr1d = np.arange(1, 21)
A = arr1d.reshape(4, 5)

# 2) extracts (5 pts)
second_col = A[:, 1]
last_row = A[-1, :]
middle_2x2 = A[1:3, 2:4]

# 3) reductions (5 pts)
row_sums = A.sum(axis=1)
col_sums = A.sum(axis=0)



# ------------------------------
#   ↓ Checks (do NOT remove!) ↓
# ------------------------------
assert A.shape == (4, 5)
assert second_col.shape == (4,)
assert last_row.shape == (5,)
assert middle_2x2.shape == (2, 2)

print("A =\n", A)
print("\nsecond_col =", second_col)
print("\nlast_row   =", last_row)
print("\nmiddle_2x2 =\n", middle_2x2)
print("\nrow_sums   =", row_sums)
print("col_sums   =", col_sums)


A =
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

second_col = [ 2  7 12 17]

last_row   = [16 17 18 19 20]

middle_2x2 =
 [[ 8  9]
 [13 14]]

row_sums   = [15 40 65 90]
col_sums   = [34 38 42 46 50]



**Explain briefly: (5 pts)** How did you choose the slice for the 2×2 sub‑matrix? Why do `axis=0` and `axis=1` correspond to columns and rows respectively?


*I used `A[1:3, 2:4]` because the first slice selects rows 1-2 and the second slice selects columns 2-3, giving a 2 by 2 block in the middle. In numpy, `axis=0` means moving down rows (along the vertical direction), and `axis=1` means moving across columns (horizontal direction).*


---
## Part 2. Useful Array Manipulations (25 pts)

In the following questions, you must get the shapes of the output correct for your answer to be accepted. The number and placement of brackets need to match!

**2.1.** Write a function that takes a list of numbers and returns a 2D NumPy array in the form of a **row vector**.  
By convention, a row vector has shape `(1, d)`, where `d` is the number of elements in the input list.

In [3]:
# Edit as needed, but keep variable/function names!
def row_vector(value_list):
    return np.array(value_list, ndmin=2)


# ------------------------------
#   ↓ Checks (do NOT remove!) ↓
# ------------------------------
v = row_vector([1, 2, 3, 4])
print(v)           # [[1 2 3 4]]
print(v.shape)     # (1, 4)

[[1 2 3 4]]
(1, 4)


**2.2.** Write a function that takes a list of numbers and returns a 2D NumPy array representing a **column vector** containing those numbers.  
By convention, a column vector has shape `(d, 1)`, where `d` is the number of elements.  
You may use your `row_vector` function.

In [4]:
# Edit as needed, but keep variable/function names!
def column_vector(value_list):
    row = row_vector(value_list)
    return row.T


# ------------------------------
#   ↓ Checks (do NOT remove!) ↓
# ------------------------------
cv = column_vector([1, 2, 3, 4])
print(cv)
print(cv.shape)   # (4, 1)

[[1]
 [2]
 [3]
 [4]]
(4, 1)


**2.3** Write a function that takes a column vector and returns its *Euclidean length* (magnitude) as a scalar (single number).  
You may **not** use `np.linalg.norm` and you may **not** use loops.

The Euclidean length of a vector $v$ is defined as:

$$
\|v\| = \sqrt{ \sum_{i=1}^{d} v_i^2 }
$$

In [5]:
# Edit as needed, but keep variable/function names!
def vector_length(col_v):
    col_v = np.asarray(col_v).reshape(-1, 1)
    return float(np.sqrt((col_v ** 2).sum()))

# ------------------------------
#   ↓ Checks (do NOT remove!) ↓
# ------------------------------
v = np.array([3,4,12]).reshape(-1,1)
print(v)
print(vector_length(v))  # 13.0

[[ 3]
 [ 4]
 [12]]
13.0


**2.4.** Write a function that takes a **column vector** and returns a **unit vector** (a vector of length 1) in the same direction.  
You may assume the input is not the zero vector and has dimension ≥ 1.  
You may **not** use loops.  
Use your previously defined `vector_length` function (do not redefine it).

In [6]:
# Edit as needed, but keep variable/function names!
def unit_vector(col_v):
    col_v = np.asarray(col_v).reshape(-1, 1)
    return col_v / vector_length(col_v)

# ------------------------------
#   ↓ Checks (do NOT remove!) ↓
# ------------------------------
v = np.array([[3], [4]])
u = unit_vector(v)
print(u)
print(vector_length(u))

[[0.6]
 [0.8]]
1.0


**2.5.** Write a function that takes a **2D NumPy array** and returns its **final column** as a 2D array (shape `(n, 1)`).  
You may **not** use loops.  
*Hint:* negative indices can be used to count from the end of the array.

In [7]:
# Edit as needed, but keep variable/function names!
def final_column(arr):
    return arr[:, [-1]]

# ------------------------------
#   ↓ Checks (do NOT remove!) ↓
# ------------------------------
arr = np.arange(1, 13).reshape(3, 4)
print(arr)
print(final_column(arr))
print(final_column(arr).shape)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 4]
 [ 8]
 [12]]
(3, 1)



---
## Part 3. Practical Simulation (25 pts)

A small company wants to simulate customer spending (in dollars). Assume spending is *normally distributed* with mean 55 and standard deviation 15.

1. Simulate the spending of 1,000 customers using `rng.normal` (use the provided `rng` for reproducibility).
2. Compute:
   - *average* simulated spending,
   - *count* of customers who spent *more than $100*,
   - *90th percentile* spending (use `np.percentile`).
3. In 3-5 lines, comment on if a normal assumption seems reasonable in retail spending, and when it might fail.

> **Deliverables:** Numeric answers and the brief discussion.


In [8]:

# Reproducibility: set a seed when simulating (do NOT remove!)
SEED = 42
rng = np.random.default_rng(SEED)

# Edit as needed, but keep variable/function names!


# 1) generate synthetic spending data (5 pts)
spending = rng.normal(loc=55, scale=15, size=1000)

# 2) compute average spending (5 pts)
avg_spending = spending.mean()

# 3) count how many values are greater than 100 (5 pts)
count_over_100 = (spending > 100).sum()

# 4) compute the 90th percentile (5 pts)
p90 = np.percentile(spending, 90)


# ------------------------------
#   ↓ Checks (do NOT remove!) ↓
# ------------------------------
print(f"Average spending: ${avg_spending:.2f}")
print(f"Customers > $100: {count_over_100}")
print(f"90th percentile:  ${p90:.2f}")


Average spending: $54.57
Customers > $100: 1
90th percentile:  $73.81


**Discussion (3-5 sentences): (5pts)**  

Is a normal distribution an appropriate model for spending data? What are its key limitations, particularly regarding non-negativity and the presence of extreme values?  

If the normal model is not ideal, what alternative distributions or modeling approaches might better capture the skewness and heavy-tailed nature of spending?  

You are encouraged to consult outside resources to support and enrich your discussion.

#### Possible answer

*A normal model is not ideal for spending because it allows negative values (which are impossible) and underestimates the probability of very large purchases. Real spending data often has a right-skewed distribution with heavy tails. Alternatives include the log-normal, gamma, or exponential distributions, which enforce non-negativity and can better capture skewness. In practice, mixture models may be used to account for both typical and rare big-ticket spending.*


---
## Part 4. Modelling (30 pts)

A lottery game picks 6 distinct numbers from 1 to 49.  
- Use NumPy to simulate $N=4400$ random tickets.  
- Estimate the probability that *at least two* players pick *exactly the same* ticket.

 To do this, you need to
1) Create function `sample_tickets(N, universe=49, k=6, rng=None) -> (N, k) int array`
to simulate N tickets (make it vectorized, do NOT use Python loops).

    > Your first move may be something like `np.array([np.sort(rng.choice(49, 6, replace=False)) + 1 for _ in range(N)])`.
    > However, this version uses for loop and is slow. Instead, use the following vectorized version:  
    > 1) Generate a matrix of size `(N, 49)` of uniform random numbers in `[0,1)`.  
    > 2) Take the 6 smallest indices -> a sample **without replacement** in each row.  
    >     - A trick is to use `np.argpartition()` which finds the k smallest indices without full sorting.  
    > 3) Sort each ticket's 6 numbers so that identical tickets compare equal.  

2) Create function `has_collision(tickets: (N, k) array) -> bool` to detect duplicates.
    - You may use `np.unique()` for this.

3) Create function  `estimate_collision_prob(N=4400, trials=100, rng=None) -> float` to estimate probability.
    - Repeat steps (1)-(2) for 100 trials and average the 0/1 collision indicator.


#### Quick guide on `np.argpartition()`

`np.argpartition(a, kth, axis=...)`  
- Performs a *partial sort*: places the element at position `kth` in its final sorted location.  
- All elements before index `kth` are smaller (order arbitrary), all elements after are larger.  
- Much faster than full sorting when you only need the smallest (or largest) `k` elements.


Let say we want to find 3 smallest elements. Then:

**For 1D**

```python
arr = np.array([30, 10, 50, 20, 40])
idx = np.argpartition(arr, 2)[:3]
```

- `np.argpartition(arr, 2)` could be `[1, 3, 0, 4, 2]`  
- The first 3 indices 1, 3, 0 point to the 3 smallest elements 10, 20, 30 (unsorted).  


**For 2D**

`keys = np.random.rand(4, 6)`      
`idx = np.argpartition(keys, 2, axis=1)[:,:3]`  

- For each row, `idx` gives the indices of the 3 smallest elements.  

In [9]:
rng = np.random.default_rng(42)

# Edit as needed, but keep variable/function names!

def sample_tickets(N, universe=49, k=6):
    keys = rng.random((N, universe))
    idx  = np.argpartition(keys, k - 1, axis=1)[:,:k]
    return np.sort(idx + 1, axis=1)

def has_collision(tickets):
    _, counts = np.unique(tickets, axis=0, return_counts=True)
    return np.any(counts > 1)

def estimate_collision_prob(N, trials):
    hits = 0
    for _ in range(trials):
        tickets = sample_tickets(N)
        hits += has_collision(tickets)
    return hits / trials

# ------------------------------
#   ↓ Checks (do NOT remove!) ↓
# ------------------------------
N = 4400
trials = 100
print(f"Estimated P(collision) for N={N} over {trials} trials: {estimate_collision_prob(N, trials):.2f}")

Estimated P(collision) for N=4400 over 100 trials: 0.52



---
## Submission Checklist

- All code cells *run without errors* from a clean kernel.
- Brief markdown reasoning included where requested.
- File name: `hw1_<LastName>_<FirstName>.ipynb`, e.g., `hw1_Kuzmin_Kiril.ipynb`.
- Submission is not zipped.

## Grading guidance (100 pts total):
- Part 1 (20 pts): 3 tasks × 5 pts each + explanation (5 pts)  
- Part 2 (25 pts): 5 tasks × 5 pts each  
- Part 3 (25 pts): 4 tasks × 5 pts each + explanation (5 pts)  
- Part 4 (30 pts): 3 functions × 10 pts each  